# Generated by Django 5.2.3 on 2025-06-20 02:17

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="customuser",
            managers=[
                ("object", django.db.models.manager.Manager()),
            ],
        ),
    ]
